"""The one place that defines what must never leave this repository.

Two mechanisms enforce the project's data posture: `tests/test_retrieval_privacy.py`
checks that committed files carry no advertisement ids or text, and
`.dockerignore` keeps the same material out of container images. Written
separately, those two lists drift, and the day they drift is the day something
leaks. Both are generated from the constants below, and a test asserts the
generated `.dockerignore` matches.
"""

from __future__ import annotations

from pathlib import Path

GENERATED_HEADER = (
    "# Generated by `make dockerignore` from src/job_market_intelligence/privacy.py.",
    "# Do not edit by hand: tests/test_docker.py fails if this file drifts from",
    "# the privacy rules that the same constants give the privacy tests.",
)

# Licensed advertisement text, anything derived from it, and credentials.
# An image layer is immutable history -- a later `rm` does not remove what an
# earlier `COPY` captured -- so these must never be copied in the first place.
PRIVATE_PATHS = (
    "data/private/",
    "data/raw/",
    "data/external/",
    "data/processed/",
    "data/public/",
    "data/labels/",
    ".env",
    ".env.*",
)

# Build inputs that are simply unnecessary in the runtime image. Excluding them
# keeps layers small and rebuilds fast; none of them are sensitive.
BUILD_EXCLUDED_PATHS = (
    ".git/",
    ".github/",
    ".venv/",
    ".pytest_cache/",
    ".ruff_cache/",
    ".claude/",
    "**/__pycache__/",
    "**/*.py[cod]",
    "**/*.egg-info/",
    ".DS_Store",
    "**/.DS_Store",
    "docs/",
    "reports/figures/",
    "*.duckdb",
    "*.joblib",
    "*.numbers",
    "Dockerfile",
    "docker-compose.yml",
    ".dockerignore",
)

# Kept in the image on purpose: the pipeline needs to run inside the container,
# and the synthetic corpus is what makes that possible without licensed data.
KEEP_PATHS = (
    "!data/synthetic/retrieval_corpus.csv",
    "!.env.example",
)


def render_dockerignore() -> str:
    """Build the .dockerignore body from the rules above."""

    lines = [
        *GENERATED_HEADER,
        "",
        "# --- Licensed data and credentials: must never enter an image layer ---",
        *PRIVATE_PATHS,
        "",
        "# --- Build noise ---",
        *BUILD_EXCLUDED_PATHS,
        "",
        "# --- Deliberate exceptions ---",
        *KEEP_PATHS,
    ]
    return "\n".join(lines) + "\n"


def dockerignore_is_current(repository_root: str | Path) -> bool:
    """Whether the committed .dockerignore matches the current rules."""

    path = Path(repository_root) / ".dockerignore"
    if not path.exists():
        return False
    return path.read_text(encoding="utf-8") == render_dockerignore()
